### ISSUE TITLE
Install Failling 

### ISSUE THREAD

**Issue by beingmohit** [ExcitableAardvark/node-cryptonight#1]
npm install --save node-cryptonight

> node-cryptonight@1.0.0 install /home/issue/node_modules/node-cryptonight
> node-gyp rebuild

make: Entering directory '/home/issue/node_modules/node-cryptonight/build'
  CXX(target) Release/obj.target/cryptonight/lib/cryptonight.o
In file included from ../lib/cryptonight.cc:32:0:
../lib/vendor/hash.h:35:10: fatal error: boost/utility/value_init.hpp: No such file or directory
 #include <boost/utility/value_init.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [cryptonight.target.mk:117: Release/obj.target/cryptonight/lib/cryptonight.o] Error 1
make: Leaving directory '/home/issue/node_modules/node-cryptonight/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.14.6-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/issue/node_modules/node-cryptonight
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-cryptonight@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-cryptonight@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ExcitableAardvark** [comment]
Hi, you need to install the development packages for OpenSSL and Boost.
On Ubuntu this is `sudo apt-get install libssl-dev libboost-all-dev`, for other distros you'll have to look online.
I will add this to the README later.
